### ISSUE TITLE
Various issues with `toodles` package

### ISSUE THREAD

**Issue by hvr** [aviaviavi/toodles#1]
I couldn't help but notice that `toodles` on Hackage is having some issues.

As can be seen on https://hackage.haskell.org/package/toodles-0.1.0.7/dependencies this package is missing version bounds which are essential for `cabal` to operate properly, and as can be seen on

https://matrix.hackage.haskell.org/#/package/toodles

![toodles](https://user-images.githubusercontent.com/285533/47035029-3c6fad80-d179-11e8-9d0e-9648494ba18f.png)

the lack of version bounds results in `cabal install toodles` failing to find good install-plans for GHC 7.8.4 through GHC 8.6.1 for different reasons.

Also, the `description` ("See the README on...") is not a proper description for your package (and Hackage will show a link to the README at the end of the description *if* the README exists; therefore that phrase is redundant), and hence this will cause poor experience for users (NB: your package won't be properly indexed by Hackage's package search feature and thus hurt its discoverability). See also [this posting](https://mail.haskell.org/pipermail/haskell-cafe/2016-November/125541.html) for more details.

Please let me know if you have any questions.

**Comment by aviaviavi** [comment]
@hvr thanks so much for taking the time to open this issue and for the thorough explanation! I'll fix these things shortly. 

An aside - I recently put another executable on Hackage that has the same issues as toodles, so you've really helped multiple repo's with this comment.

**Comment by hvr** [comment]
@aviaviavi I'm afraid that lower bounds aren't enough, the build matrix is still read

But I notice you're using Stack which can generate/infer bounds from the stackage collection you used; e.g. you can add `pvp-bounds: both` to your stack.yaml file

Another tool is `staversion` (https://github.com/debug-ito/staversion) if you need more flexibility

(btw, are you aware of https://github.com/haskell-infra/hackage-trustees/blob/master/revisions-information.md ?)

**Comment by aviaviavi** [comment]
@hvr ah these suggestions are very helpful, just what I was looking for! I had no idea what I was doing when trying to fix this, and my last package upload was mostly a shot in the dark. I'll try out these other approaches soon.

**Comment by aviaviavi** [comment]
Also good to know one can change these bounds without uploading a new version, didn't know!

**Comment by aviaviavi** [comment]
@hvr question for you - because this is just a binary distribution and not a library, in your opinion is there much harm in just pinning down most or all of the dependencies to exact versions?

**Comment by aviaviavi** [comment]
Well, with pinning them down exactly, this is building properly with ghc-8.4. Open getting this to work with other versions too if that's straightforward to do given a working stack project? If it's too much of a headache I may put that off until I know that people actually want to use this tool :)

**Comment by aviaviavi** [comment]
closing for now, now that this is cabal install-able, i'll make improvements to getting it to work with more versions now. feel free to re-open if there are other things to address.

thanks again @hvr !
