### ISSUE TITLE
delete >>= edit -> wrong entry duplicate

### ISSUE THREAD

**Issue by damiencourousse** [aviaviavi/toodles#13]
hello,

deleting an entry, and then editing another entry farther in the same source file leads to creating a duplicate of the edited entry.

steps to reproduce:
```
$ echo "-- TODO issue 1" >> test.hs
$ echo "" >> test.hs
$ echo "-- TODO issue 2" >> test.hs
```

- open toodles UI
- delete issue 1
- edit and modify issue 2
- issue 2 is now duplicated in file `test.hs`:
```
$ cat test.hs

-- TODO issue 2
-- TODO (|#test) - issue 2
```

thanks,

**Comment by aviaviavi** [comment]
Ha interesting, nice catch! Not entirely surprising to see a bug like this, the editing code logic was fairly tricky.

**Comment by aviaviavi** [comment]
Looks fixed in master now. Please re-open if this pops up again or doesn't appear fixed
