### ISSUE TITLE
Precompiled Windows Distribution

### ISSUE THREAD

**Issue by SilasReinagel** [aviaviavi/toodles#18]
For those of us who are using work machines that are heavily crippled by anti-virus software, it would be very useful to have a Windows distribution of toodles available.

**Comment by aviaviavi** [comment]
Thanks for the suggestion! I'm a bit out of the loop on windows, is a docker image a viable solution for  Windows? I don't currently have access to a windows machine, so it's going to be a bit of work / time before I get this compiling on Windows myself

**Comment by SilasReinagel** [comment]
That would probably work. If you build one, I would be happy to use it.

**Comment by aviaviavi** [comment]
Great! @mrala mentioned working on this in #11, so hopefully that will be available soon

**Comment by aviaviavi** [comment]
@SilasReinagel a Dockerfile is now available, curious if this is working for you on windows?

**Comment by aviaviavi** [comment]
Now that there is a precompiled version bundled in a docker image, I'm going to mark this as closed. If there are problems getting that working, feel free to re-open or make a new issue
