### ISSUE TITLE
Ignoring paths doesn't work when invoked with directory (-d) argument

### ISSUE THREAD

**Issue by mgalgs** [aviaviavi/toodles#23]
When I try to ignore a path it doesn't seem to work if I invoke `toodles` from outside the project path using the `-d` argument.

I have a project at `~/sites/str-prod` where I'd like to run `toodles`.  I invoked `toodles` with:

```
$ toodles -d ~/sites/str-prod
```

Here's what I'm trying to ignore:

```
ignore:
  - static/piu/avenxo
```

but I'm still seeing files under this `avenxo` path in my TODO list:

![image](https://user-images.githubusercontent.com/152014/47578269-d7951f80-d8fd-11e8-8e31-b0ba824cf22f.png)

However, when I invoke `toodles` from within the project directory it seems to work (i.e. I don't see any TODOs under `avenxo`):

```
$ cd ~/sites/str-prod
$ toodles
```

**Comment by aviaviavi** [comment]
@mgalgs If you update toodles to the latest version, do you still see this? I just tried to reproduce this a few times but wasn't seeing this behavior. If you are still seeing it I will dig a little more

**Comment by mgalgs** [comment]
Weird... Just tried again (without updating `toodles`) and it's working fine now.  Must have been user error.  Sorry for the noise!

**Comment by aviaviavi** [comment]
No worries!
