### ISSUE TITLE
Custom Attributes example

### ISSUE THREAD

**Issue by vlatkoB** [aviaviavi/toodles#3]
Hi, just testing this nice app, but can't figure what format should be used for `Custom Attributes` in web interface. Always getting `Parse error, check your formatting and try again`.
Tried `x`, `#x`, `#x=y`, but nothing works

**Comment by aviaviavi** [comment]
Ah sorry for the confusion! Custom attributes are

`key=val,key2=val2`

I'll make sure this is documented better

**Comment by aviaviavi** [comment]
Oops wait, you've uncovered an issue! 

The toodles server looks for `key=val`, but the UI demands `key:val`. I'll fix :)

**Comment by vlatkoB** [comment]
I'd also like to mention that web UI on `edit` action doesn't populate fields with current values.

**Comment by aviaviavi** [comment]
Right, this was a choice I made more because it's currently an add-only situation. It wasn't clear what the right way to handle edits that would be applied to multiple todo's at once. 

I think that's an issue that can be fixed when #5 is addressed

**Comment by aviaviavi** [comment]
Ok the UI properly expects `=`, so `x=y` works via the UI now
