### ISSUE TITLE
'stack install toodles' downloads 3,5GB of stuff

### ISSUE THREAD

**Issue by davekch** [aviaviavi/toodles#45]
This is not an issue with your software, just a question.
I previously didn't have stack so I [installed it](https://docs.haskellstack.org/en/stable/install_and_upgrade/). Running `stack install toodles` downloaded a full 3,5GB of stuff to ~/.stack. Toodles seems to be rather lightweight so I was not suspecting that. What's that for? Can I safely remove this without breaking your application?

**Comment by vlatkoB** [comment]
That's GHC compiler and libs. After you have the binary, you can remove those, but maybe you should keep it. `toodles' is currently in fast pace mode, so when you'll want to install newer source in a few days, all that will be downloaded again.

**Comment by davekch** [comment]
ok thanks for the information!
