### ISSUE TITLE
Installing with Stack base dependency issue

### ISSUE THREAD

**Issue by DaveVanRijn** [aviaviavi/toodles#59]
Hi,
I just tried to install toodles using the latest version of Stack (windows), which failed with the following message: 

`In the dependencies for directory-1.3.1.5:
    base-4.12.0.0 from stack configuration does not match >=4.5 && <4.12  (latest matching version
                  is 4.11.1.0)
needed due to toodles-1.0.2 -> directory-1.3.1.5
`

`Build requires unattainable version of base. Since base is a part of GHC, you most likely need
    to use a different GHC version with the matching base.`
It looks like toodles does not support the latest version of Stack (yet). Any suggestions on how to fix this? Or should the README specify a specific version of Stack/GHC to be used?

**Comment by aviaviavi** [comment]
@DaveVanRijn which stackage lts are you trying to use? 

toodles is set to build with lts-12.14. you can change your global stack configuration to use this and then it should build. i can edit the docs to reflect this.

**Comment by aviaviavi** [comment]
ok the readme is update to include the `resolver` flag in the stack command. will open a separate issue to make this build with the latest lts

**Comment by DaveVanRijn** [comment]
@aviaviavi Thanks, it works great!
