### ISSUE TITLE
Running Toodles on a static file server

### ISSUE THREAD

**Issue by jviotti** [aviaviavi/toodles#63]
Hey there! Asking here as I couldn't answer this from the docs: is there a way we can run Toodles on a project (Node.js in this case), and generate a bunch of HTML/CSS/JS files that we can host along with other static reports we generate on every PR?

**Comment by aviaviavi** [comment]
Hi @jviotti, thanks for asking! Currently there isn't anything that gets all the way to static html/css/js, but there is a (poorly documented) `--no-server` flag you can pass to toodles which will make it print the TODO's to stdout and exit. An issue is that there is other unrelated output that toodles prints out before, so in its current state it won't make for a great report without some tweaks. 

Two options here:
- I'd be happy to accept a PR for these changes if you're up to it. I will help however I can to get you going.
- I or someone else will get to it when time permits, but it probably won't be immediately. If you can list any other relevant details of what you're envisioning, just describe that here in this issue.

**Comment by jviotti** [comment]
Closing stale issues
