### ISSUE TITLE
Scarf OSX build has build-specific path

### ISSUE THREAD

**Issue by arpd** [aviaviavi/toodles#66]
Hi, I've installed toodles using scarf on two platforms now; Ubuntu and OSX, and run in to the same issue:
```
§ toodles
serving on 9001
/Users/avipress/side/toodles/.stack-work/install/x86_64-osx/lts-12.14/8.4.3/share/x86_64-osx-ghc-8.4.3/toodles-1.2.1/web/html/index.html: openFile: does not exist (No such file or directory)
^Cuser interrupt
```

It looks like toodles is expecting to find something at a path that existed on the system used to build the application.

**Comment by aviaviavi** [comment]
Oh yikes. Something must have been messed up from the latest deployment. How are you installing toodles?

**Comment by aviaviavi** [comment]
I'm fixing this now, apologies for the inconvenience, I imagine this is from the Scarf installation. In the meantime, toodles should still work as expected if you install via stack.

**Comment by aviaviavi** [comment]
Ok things should be fixed when installed from Scarf. Thanks for opening this @arpd!

**Comment by aviaviavi** [comment]
Scarf is still in its infancy, so you'll likely need to delete your ~/.scarf/scarf-package.json and reinstall toodles for now
