### ISSUE TITLE
Scarf install on OSX does not work

### ISSUE THREAD

**Issue by arpd** [aviaviavi/toodles#67]
Hello again; #66 was fixed, but now there is a different error:
```
~/p/tremulous-game-logic § scarf install toodles
Installing toodles
Generating dependency list
Installing 1 package(s): [toodles]
Downloading
Extracting...
Copying...
Done
~/p/tremulous-game-logic § toodles -h
b7b8b342-d117-45d1-b46b-ba949d4191e4: user error (Couldn't initialize toodles, no valid data directory found. Please file a bug on Github.)
~/p/tremulous-game-logic §
```

**Comment by aviaviavi** [comment]
Hi @arpd I'm sorry you've been running into these issues and really really appreciate you opening these issues so we can get them fixed. I've uploaded a new version of toodles and also a new version of Scarf that seem to fix things on my end. Could you try:

```bash
$ scarf upgrade
$ scarf install toodles
```

And try running toodles again?

**Comment by arpd** [comment]
Hi @aviaviavi; It's working now, thanks for the help!

**Comment by aviaviavi** [comment]
Awesome! Sure thing, thank you both for reporting these issues and for your patience :D
